apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampletest-deployment
spec:
  selector:
    matchLabels:
      app: sampletest
  template:
    metadata:
      labels:
        app: sampletest
    spec:
      containers:
      - name: sampletest
        image: sampletest:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80 
        env:
          - name: MongoDbSettings__Host
            value: mongodb-service
          - name: MongodbSettings__Password
            valueFrom:
              secretKeyRef:
                name: sampletest-secrets
                key: mongodb-password
        livenessProbe:
          httpGet:
            path: /health/alive
            port: 80 
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80

---


apiVersion: v1
kind: Service
metadata:
  name: sampletest-service
spec:
  type: LoadBalancer
  selector:
    app: sampletest
  ports:
  - port: 4000
    targetPort: 80
        